### ISSUE TITLE
Unhandled exception System.NullReferenceException

### ISSUE THREAD

**Issue by dhaselb** [cramerlab/warpcraft#1]
Hi I was trying warpcraft on my data and somehow dont get it running.  This is what I did and what I get: 

warpcraft --input run_data.star --particlediameter 300 --angpix 1.16
Executing with the following parameters:
  Input model: C:\Users\david.haselbach\Desktop\warpcraft-test\run_data.star
  Particle diameter: 300 A
  Pixel size: 1,16 A
  Iterations: 5
  Steps per iteration: 40
  Batch size: 300
  Threads per GPU: 1

  Pre-read particles: True

  Output B-factor: 0 A^2
  Local resolution window size: 40 px
  Local resolution FSC threshold: 0,5

  Dilate mask for fine model: 5 px
  Body overlap region: 2 px

  Init coarse atom model with:
  Number of coarse atoms: 5000
  Oversample fine atoms by: 4x
  Update modes after each iteration: False
  Normal modes: 10

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Warp.Star..ctor(String path, String tableName) in D:\Dev\warp\WarpLib\Star.cs:line 54
   at Warp.Craft.Program.Main(String[] args) in D:\Dev\warpcraft\Program.cs:line 121

best, 

David

**Comment by charbj** [comment]
Yes, I have had an identical issue. Any help would be very appreciated. Dying to try WarpCraft.

**Comment by biochem-fan** [comment]
It seems that the required input is not RELION's STAR file. I am using something like below but I hope @dtegunov could provide a sample input.

```
data_map

loop_
_wrpMapHalf1 #1
_wrpMapHalf2 #2
_wrpFrankenmap #3
_wrpParticles #4
run_half1_class001_unfil.mrc run_half2_class001_unfil.mrc run_class001.mrc run_data.star

data_models


data_bodies

loop_
_wrpBodyMaskHard #1
mask.mrc
```
